import { Token } from "@redux/models/TokenModels";

//
export const ICRC1systemAssets: Array<Token> = [
  {
    id_number: 10000,
    symbol: "ICP",
    name: "Internet Computer",
    tokenSymbol: "ICP",
    tokenName: "Internet Computer",
    address: "ryjl3-tyaaa-aaaaa-aaaba-cai",
    decimal: "8",
    shortDecimal: "8",
    fee: "10000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10001,
    symbol: "ckBTC",
    name: "ckBTC",
    tokenSymbol: "ckBTC",
    tokenName: "ckBTC",
    address: "mxzaz-hqaaa-aaaar-qaada-cai",
    decimal: "8",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "n5wcd-faaaa-aaaar-qaaea-cai",
  },
  {
    id_number: 10002,
    symbol: "ckETH",
    name: "ckETH",
    tokenName: "ckETH",
    tokenSymbol: "ckETH",
    address: "ss2fx-dyaaa-aaaar-qacoq-cai",
    decimal: "18",
    shortDecimal: "18",
    fee: "2000000000000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "s3zol-vqaaa-aaaar-qacpa-cai",
  },
  {
    id_number: 10003,
    address: "2ouva-viaaa-aaaaq-aaamq-cai",
    symbol: "CHAT",
    name: "openChat",
    tokenSymbol: "CHAT",
    tokenName: "openChat",
    decimal: "8",
    shortDecimal: "8",
    fee: "100000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "2awyi-oyaaa-aaaaq-aaanq-cai",
  },
  {
    id_number: 10004,
    address: "73mez-iiaaa-aaaaq-aaasq-cai",
    symbol: "KINIC",
    name: "Kinic",
    tokenSymbol: "KINIC",
    tokenName: "Kinic",
    decimal: "8",
    shortDecimal: "8",
    fee: "10000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "7vojr-tyaaa-aaaaq-aaatq-cai",
  },
  {
    id_number: 10005,
    address: "zfcdd-tqaaa-aaaaq-aaaga-cai",
    symbol: "SNS1",
    name: "Draggins",
    tokenSymbol: "SNS1",
    tokenName: "Draggins",
    decimal: "8",
    shortDecimal: "8",
    fee: "1000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "zlaol-iaaaa-aaaaq-aaaha-cai",
  },
  {
    id_number: 10007,
    address: "oh54a-baaaa-aaaap-abryq-cai",
    symbol: "GLDT",
    name: "Gold token",
    tokenSymbol: "GLDT",
    tokenName: "Gold token",
    decimal: "8",
    shortDecimal: "8",
    fee: "10000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "oo6x4-xiaaa-aaaap-abrza-cai",
  },
  {
    id_number: 10008,
    address: "jwcfb-hyaaa-aaaaj-aac4q-cai",
    symbol: "OGY",
    name: "Origyn",
    tokenSymbol: "OGY",
    tokenName: "Origyn",
    decimal: "8",
    shortDecimal: "8",
    fee: "200000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "",
  },
  {
    id_number: 10009,
    address: "6rdgd-kyaaa-aaaaq-aaavq-cai",
    symbol: "HOT",
    name: "Hot or Not",
    tokenSymbol: "HOT",
    tokenName: "Hot or Not",
    decimal: "8",
    shortDecimal: "8",
    fee: "100000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "6dfr2-giaaa-aaaaq-aaawq-cai",
  },
  {
    id_number: 10010,
    address: "tyyy3-4aaaa-aaaaq-aab7a-cai",
    symbol: "GLDGov",
    name: "Gold Governance Token",
    tokenSymbol: "GLDGov",
    tokenName: "Gold Governance Token",
    decimal: "8",
    shortDecimal: "8",
    fee: "100000",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
    index: "efv5g-kqaaa-aaaaq-aacaa-cai",
  },
];

export const ICRC2systemAssets: Array<Token> = [
  {
    id_number: 10000,
    symbol: "W2E",
    name: "Waste2Earn",
    tokenSymbol: "W2E",
    tokenName: "W2E",
    address: "n6j6v-cqaaa-aaaam-acjma-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10001,
    symbol: "wPl",
    name: "Waste Plastic",
    tokenSymbol: "wPlastic",
    tokenName: "wPlastic",
    address: "mbbnc-biaaa-aaaam-acjiq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10002,
    symbol: "wPr",
    name: "Waste Paper",
    tokenSymbol: "wPaper",
    tokenName: "wPaper",
    address: "mpdak-2yaaa-aaaam-acjjq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10003,
    symbol: "wG",
    name: "Waste Glass",
    tokenSymbol: "wGlass",
    tokenName: "wGlass",
    address: "m5fxt-wiaaa-aaaam-acjkq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10004,
    symbol: "wM",
    name: "Waste Metal",
    tokenSymbol: "wMetal",
    tokenName: "wMetal",
    address: "m2erh-3qaaa-aaaam-acjka-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10005,
    symbol: "wOx",
    name: "Waste Organic",
    tokenSymbol: "wOrganic",
    tokenName: "wOrganic",
    address: "mug4p-aaaaa-aaaam-acjla-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
  {
    id_number: 10006,
    symbol: "eW",
    name: "Electronic Waste",
    tokenSymbol: "eWaste",
    tokenName: "eWaste",
    address: "mth23-nyaaa-aaaam-acjlq-cai ",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    subAccounts: [{ numb: "0", name: "Default", amount: "0", currency_amount: "0" }],
  },
];

//
export const defaultTokens: Token[] = [
  {
    id_number: 0,
    symbol: "ICP",
    name: "Internet Computer",
    tokenSymbol: "ICP",
    tokenName: "Internet Computer",
    address: "ryjl3-tyaaa-aaaaa-aaaba-cai",
    decimal: "8",
    shortDecimal: "8",
    fee: "10000",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 1,
    symbol: "W2E",
    name: "Waste2Earn",
    tokenSymbol: "W2E",
    tokenName: "W2E",
    address: "n6j6v-cqaaa-aaaam-acjma-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "n6j6v-cqaaa-aaaam-acjma-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 2,
    symbol: "wPl",
    name: "Waste Plastic",
    tokenSymbol: "wPlastic",
    tokenName: "wPlastic",
    address: "mbbnc-biaaa-aaaam-acjiq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "mbbnc-biaaa-aaaam-acjiq-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 3,
    symbol: "wPr",
    name: "Waste Paper",
    tokenSymbol: "wPaper",
    tokenName: "wPaper",
    address: "mpdak-2yaaa-aaaam-acjjq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "mpdak-2yaaa-aaaam-acjjq-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 4,
    symbol: "wM",
    name: "Waste Metal",
    tokenSymbol: "wMetal",
    tokenName: "wMetal",
    address: "m2erh-3qaaa-aaaam-acjka-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "m2erh-3qaaa-aaaam-acjka-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 5,
    symbol: "wG",
    name: "Waste Glass",
    tokenSymbol: "wGlass",
    tokenName: "wGlass",
    address: "m5fxt-wiaaa-aaaam-acjkq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "m5fxt-wiaaa-aaaam-acjkq-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 6,
    symbol: "wOx",
    name: "Waste Organic",
    tokenSymbol: "wOrganic",
    tokenName: "wOrganic",
    address: "mug4p-aaaaa-aaaam-acjla-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "mug4p-aaaaa-aaaam-acjla-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
  {
    id_number: 7,
    symbol: "eW",
    name: "Electronic Waste",
    tokenSymbol: "eWaste",
    tokenName: "eWaste",
    address: "mth23-nyaaa-aaaam-acjlq-cai",
    decimal: "18",
    shortDecimal: "8",
    fee: "10",
    index: "mth23-nyaaa-aaaam-acjlq-cai",
    subAccounts: [
      {
        name: "Default",
        numb: "0x0",
        amount: "0",
        currency_amount: "0",
      },
    ],
  },
];
